#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting and formatting checks before pushing

echo "Running formatting checks..."

# Run formatting
prettier --check "**/*.html" "**/*.scss" "**/*.ts" || exit 1

echo "formatting checks passed."

yarn format:fix

